#!/usr/bin/env python3
# Copyright: Ankitects Pty Ltd and contributors
# License: GNU AGPL, version 3 or later; http://www.gnu.org/licenses/agpl.html

"""Build a DEMO collection driven by the seeded synthetic persona.

    make seed-persona                 # -> out/demo-persona.anki2
    make seed-persona ARGS="--path /tmp/demo.anki2 --seed 20260703"

This is the honest "reasonable data": it creates a real Anki collection, builds
the tagged Exam P deck, then feeds it a synthetic study history (graded revlog
rows + graded practice tests) generated by ``anki.speedrun.persona``. Every
number the app then shows is computed by the real engine on real collection
state; the history is just synthetic and always labelled ``synthetic demo
persona``. Same seed -> identical collection -> identical numbers.

Open the result in the app (File -> Open, or point the profile at it) and the
readiness dashboard shows a real, persona-labelled score with its honesty bundle.
"""

from __future__ import annotations

import argparse
import os
import sys
import time

_REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
for _p in (os.path.join(_REPO, "pylib"), os.path.join(_REPO, "out", "pylib")):
    if _p not in sys.path:
        sys.path.insert(0, _p)

import anki.collection  # noqa: E402,F401  (preload to avoid a circular import)
from anki import speedrun_pb2  # noqa: E402
from anki.cards import FSRSMemoryState  # noqa: E402
from anki.collection import Collection  # noqa: E402
from anki.consts import CARD_TYPE_REV, QUEUE_TYPE_REV  # noqa: E402
from anki.speedrun import (  # noqa: E402
    expected_subtopic_tags,
    set_exam_date,
    unit_weights,
)
from anki.speedrun.persona import (  # noqa: E402
    SYNTHETIC_LABEL,
    answer_items,
    default_persona,
    review_grades,
)
from anki.speedrun.practice_test import (  # noqa: E402
    assemble_test,
    grade,
    record_test,
)
from anki.speedrun.seed import build_deck  # noqa: E402
from anki.speedrun.soa_sample import load_sample_items  # noqa: E402


def insert_reviews(col: Collection, persona, per_subtopic: int) -> int:
    """Give each studied card a realistic FSRS review history so the collection
    carries real MEMORY state, not just a review count.

    For each subtopic's cards we synthesise a plausible study history: graded
    revlog rows spaced over past days with growing intervals (reset on a fail),
    with eases from the persona (1 = fail, 3 = pass) so per-subtopic accuracy
    reflects the persona's skill. We then let the engine compute each card's FSRS
    memory state (`compute_memory_state`) from that history and mark the card as a
    review card last seen a few days ago. That makes the Memory signal (mean FSRS
    retrievability, with a 10th-90th band) a MEASURED value with a real range,
    instead of abstaining. Deterministic given the persona seed. Returns the total
    revlog rows inserted.
    """
    day_ms = 86_400_000
    today = col.sched.today
    now_secs = int(time.time())
    now_day_ms = (now_secs * 1000 // day_ms) * day_ms
    total = 0
    card_seq = 0
    for tag in expected_subtopic_tags():
        cids = col.find_cards(f'"tag:{tag}"')
        if not cids:
            continue
        grades = review_grades(persona, tag, per_subtopic)
        by_card: dict = {}
        for i, ease in enumerate(grades):
            by_card.setdefault(cids[i % len(cids)], []).append(ease)
        for cid, gs in by_card.items():
            # Interval scheduled AT each review (the wait until the next one),
            # growing on a pass and resetting on a fail; capped so stability stays
            # realistic rather than saturating retrievability at 1.0.
            gaps: list[int] = []
            iv = 1
            for g in gs:
                gaps.append(iv)
                iv = 1 if g == 1 else min(40, max(1, round(iv * 1.6)))
            pos = [sum(gaps[:k]) for k in range(len(gs))]
            last_ivl = gaps[-1]
            # Days since the last review = a fraction of the last interval, varied
            # per card so retrievability decays to a real spread (not all 1.0).
            frac = 0.4 + 1.3 * ((card_seq * 7) % 10) / 10.0
            elapsed = max(1, round(last_ivl * frac))
            offset = card_seq * 1000  # unique sub-day offset -> unique revlog ids
            rows = []
            for k, ease in enumerate(gs):
                days_ago = elapsed + (pos[-1] - pos[k])
                ts = now_day_ms - days_ago * day_ms + offset + k
                last = gaps[k - 1] if k > 0 else 0
                rows.append((int(ts), cid, -1, ease, gaps[k], last, 2500, 1500, 1))
            col.db.executemany(
                "insert into revlog (id,cid,usn,ease,ivl,lastIvl,factor,time,type) "
                "values (?,?,?,?,?,?,?,?,?)",
                rows,
            )
            total += len(rows)
            card = col.get_card(cid)
            card.type = CARD_TYPE_REV
            card.queue = QUEUE_TYPE_REV
            card.ivl = last_ivl
            card.due = today - elapsed + last_ivl
            state = col.compute_memory_state(cid)
            if state.stability:
                card.memory_state = FSRSMemoryState(
                    stability=state.stability, difficulty=state.difficulty
                )
                card.last_review_time = now_secs - elapsed * 86_400
            col.update_card(card)
            card_seq += 1
    return total


def take_tests(col: Collection, persona, n_tests: int, size: int) -> None:
    """Have the persona sit ``n_tests`` section-weighted practice tests and
    record each graded result into config (so readiness has evidence)."""
    items = load_sample_items()
    for t in range(n_tests):
        test = assemble_test(n=size, seed=1000 + t, items=items)
        responses = {
            r.item_id: r.correct
            for r in answer_items(persona, test, seed_salt=f"test-{t}")
        }
        result = grade(test, responses, label=SYNTHETIC_LABEL)
        record_test(col, result)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--path", default=os.path.join(_REPO, "out", "demo-persona.anki2")
    )
    parser.add_argument("--seed", type=int, default=None, help="persona seed")
    parser.add_argument("--per-subtopic", type=int, default=14)
    parser.add_argument("--tests", type=int, default=4)
    parser.add_argument("--test-size", type=int, default=30)
    args = parser.parse_args()

    if os.path.exists(args.path):
        os.remove(args.path)
    os.makedirs(os.path.dirname(os.path.abspath(args.path)), exist_ok=True)

    persona = default_persona() if args.seed is None else default_persona(args.seed)

    print("=" * 72)
    print(
        f"Building DEMO collection for the {SYNTHETIC_LABEL!r} (seed {persona.seed})."
    )
    print("All numbers below are computed by the real engine on synthetic study")
    print("history; reproducible from the seed. NOT a real student.")
    print("=" * 72)

    col = Collection(args.path)
    try:
        added = build_deck(col)
        reviews = insert_reviews(col, persona, args.per_subtopic)
        take_tests(col, persona, args.tests, args.test_size)
        # A target exam date 60 days out, so the pace card is populated too.
        set_exam_date(
            col, time.strftime("%Y-%m-%d", time.localtime(time.time() + 60 * 86400))
        )

        units = [
            speedrun_pb2.UnitWeight(unit_id=u, weight=w) for u, w in unit_weights()
        ]
        result = col._backend.compute_readiness(
            expected_subtopics=expected_subtopic_tags(), units=units
        )
        print(f"\ncards added        : {added}")
        print(f"graded revlog rows : {reviews}")
        which = result.WhichOneof("value")
        if which == "score":
            s = result.score
            print("\nReadiness (synthetic demo persona):")
            print(
                f"  projected 0-10   : {s.point:.1f}  (range {s.low:.1f}-{s.high:.1f})"
            )
            print(f"  P(pass)          : {s.pass_probability:.0%}")
            print(
                f"  coverage         : {s.coverage_pct:.0%}   confidence {s.confidence:.2f}"
            )
            print(f"  next best action : {s.next_best_action}")
        else:
            ns = result.no_score
            print("\nReadiness: NoScore (give-up rule)")
            print(f"  reason           : {ns.reason}")
            print(
                f"  graded reviews   : {ns.graded_reviews}   coverage {ns.coverage_pct:.0%}"
            )
        print(f"\nWrote {args.path}")
        print("Open it in the app to see the three signals + honesty bundle.")
    finally:
        col.close()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
